services:
  guacd_guacamole:
    container_name: guacd_guacamole
    hostname: guacd_guacamole
    image: guacamole/guacd:1.5.5
    networks:
      - net-guacamole
    restart: always
    volumes:
      - ./guacamole/guacd/drive:/drive
      - ./guacamole/guacd/record:/var/lib/guacamole/recordings
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.clean-recordings.schedule: "0 0 * * *"
#      ofelia.job-exec.clean-recordings.command: "find /var/lib/guacamole/recordings -mindepth 1 -maxdepth 1 -type d -mtime +1 -exec rm -r {} +"
      ofelia.job-exec.clean-recordings.command: "find /var/lib/guacamole/recordings -mindepth 1 -maxdepth 1 -type d -mtime +15 -exec rm -r {} +"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"

  postgres_guacamole:
    container_name: postgres_guacamole
    hostname: postgres_guacamole
    image: postgres:17.2-alpine3.21
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: "${POSTGRESQL_DATABASE}"
      POSTGRES_USER: "${POSTGRESQL_USER}"
      POSTGRES_PASSWORD: "${POSTGRESQL_PASSWORD}"
    networks:
      - net-guacamole
    restart: always
    volumes:
      - ./guacamole/db/init:/docker-entrypoint-initdb.d
      - ./guacamole/db/data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"

  guacamole:
    container_name: guacamole
    hostname: guacamole
    image: guacamole/guacamole:1.5.5
    depends_on:
      - guacd_guacamole
      - postgres_guacamole
    environment:
      GUACD_HOSTNAME: "${GUACD_HOSTNAME}"
      POSTGRESQL_DATABASE: "${POSTGRESQL_DATABASE}"
      POSTGRESQL_HOSTNAME: "${POSTGRESQL_HOSTNAME}"
      POSTGRESQL_USER: "${POSTGRESQL_USER}"
      POSTGRESQL_PASSWORD: "${POSTGRESQL_PASSWORD}"
      POSTGRESQL_AUTO_CREATE_ACCOUNTS: true
      RECORDING_SEARCH_PATH: '/var/lib/guacamole/recordings'
      POSTGRESQL_DEFAULT_MAX_GROUP_CONNECTIONS_PER_USER: 3
      POSTGRESQL_DEFAULT_MAX_CONNECTIONS_PER_USER: 1
      POSTGRESQL_DEFAULT_MAX_GROUP_CONNECTIONS: 3
      POSTGRESQL_DEFAULT_MAX_CONNECTIONS: 1
      POSTGRESQL_ABSOLUTE_MAX_CONNECTIONS: 10  
      REMOTE_IP_VALVE_ENABLE: true
    volumes:
      - ./guacamole/guacd/drive:/drive
      - ./guacamole/guacd/record:/var/lib/guacamole/recordings
    networks:
      - net-guacamole
      - npm-network
    ports:
      - "8080:8080"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"

  ofelia_guacamole:
    image: mcuadros/ofelia:0.3
    container_name: ofelia_guacamole
    hostname: ofelia_guacamole
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    userns_mode: "host"        
    depends_on:
      - guacd_guacamole 
    command: daemon --docker
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"      
    networks:
      - net-guacamole

networks:
  net-guacamole:
    driver: bridge
  npm-network:
    name: npm-network
    external: true 
